import{a as c,i as a}from"./assets/vendor-2dcf4ad5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const l of t)if(l.type==="childList")for(const s of l.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const l={};return t.integrity&&(l.integrity=t.integrity),t.referrerpolicy&&(l.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?l.credentials="include":t.crossorigin==="anonymous"?l.credentials="omit":l.credentials="same-origin",l}function i(t){if(t.ep)return;t.ep=!0;const l=n(t);fetch(t.href,l)}})();c.defaults.headers.common["x-api-key"]="live_tTd2DeRlMjmrwT0GvEPrcbWJhw1aaGd3xLGjpt1jvcgogKWXbIOuJRg3sms8DZoD";function d(){return c.get("https://api.thecatapi.com/v1/breeds").then(o=>o.data)}function u(o){return c.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${o}`).then(r=>r.data[0])}const e={breedSelect:document.querySelector(".breed-select"),loaderText:document.querySelector(".loader"),errorText:document.querySelector(".error"),catInfoSection:document.querySelector(".cat-info"),refreshButton:document.querySelector(".refresh-button")};e.refreshButton.style.display="none";d().then(o=>{o.forEach(r=>{const n=document.createElement("option");n.value=r.id,n.text=r.name,e.breedSelect.appendChild(n)}),e.loaderText.style.display="none",e.breedSelect.style.display="block"}).catch(o=>{console.error("Error fetching breeds:",o),e.loaderText.style.display="none",e.breedSelect.style.display="none",a.error({error:"Error",title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!"}),e.refreshButton.style.display="block"});e.breedSelect.addEventListener("change",p);function p(){const o=e.breedSelect.value;if(console.log(o),o==="0"){location.href="./index.html";return}e.loaderText.style.display="block",e.catInfoSection.style.display="none",e.breedSelect.style.display="none",u(o).then(r=>{const n=r.breeds[0];e.catInfoSection.innerHTML=`
            <img src="${r.url}" alt="${n.name}" class="cat-img" width="450px" />
            <div class="cat-info-accent">
                <h2>${n.name}</h2>
                <p>${n.description}</p>
                <p><strong>Temperament:</strong> ${n.temperament}</p>
                <a href="${n.wikipedia_url}" target="_blank" class="more-info-button">Read more</a>
            </div>
            `,e.loaderText.style.display="none",e.catInfoSection.style.display="flex",e.breedSelect.style.display="block"}).catch(r=>{console.error("Error fetching breeds:",r),e.loaderText.style.display="none",e.breedSelect.style.display="none",a.error({error:"Error",title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!"}),e.refreshButton.style.display="block"})}
//# sourceMappingURL=commonHelpers.js.map
