import{a as i,i as a}from"./assets/vendor-2dcf4ad5.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&l(c)}).observe(document,{childList:!0,subtree:!0});function e(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function l(r){if(r.ep)return;r.ep=!0;const n=e(r);fetch(r.href,n)}})();i.defaults.headers.common["x-api-key"]="live_tTd2DeRlMjmrwT0GvEPrcbWJhw1aaGd3xLGjpt1jvcgogKWXbIOuJRg3sms8DZoD";function d(){return new Promise((s,o)=>{fetch("https://api.thecatapi.com/v1/breeds").then(e=>{if(!e.ok)throw new Error("Network response was not ok");return e.json()}).then(e=>{const l=e.map(r=>({id:r.id,name:r.name}));s(l)}).catch(e=>{o(e)})})}function u(s){return new Promise((o,e)=>{i.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${s}`).then(l=>{o(l.data[0])}).catch(l=>{e(l)})})}const t={breedSelect:document.querySelector(".breed-select"),loaderText:document.querySelector(".loader"),errorText:document.querySelector(".error"),catInfoSection:document.querySelector(".cat-info"),refreshButton:document.querySelector(".refresh-button")};t.refreshButton.style.display="none";d().then(s=>{s.forEach(o=>{const e=document.createElement("option");e.value=o.id,e.text=o.name,t.breedSelect.appendChild(e)}),t.loaderText.style.display="none",t.breedSelect.style.display="block"}).catch(s=>{console.error("Error fetching breeds:",s),t.loaderText.style.display="none",t.breedSelect.style.display="none",a.error({error:"Error",title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!"}),t.refreshButton.style.display="block"});t.breedSelect.addEventListener("change",p);function p(){const s=t.breedSelect.value;t.loaderText.style.display="block",t.catInfoSection.style.display="none",t.breedSelect.style.display="none",u(s).then(o=>{const e=o.breeds[0];t.catInfoSection.innerHTML=`
            <img src="${o.url}" alt="${e.name}" class="cat-img" width="450px" />
            <div class="cat-info-accent">
                <h2>${e.name}</h2>
                <p>${e.description}</p>
                <p><strong>Temperament:</strong> ${e.temperament}</p>
                <a href="${e.wikipedia_url}" target="_blank" class="more-info-button">Read more</a>
            </div>
            `,t.loaderText.style.display="none",t.catInfoSection.style.display="flex",t.breedSelect.style.display="block"}).catch(o=>{console.error("Error fetching breeds:",o),t.loaderText.style.display="none",t.breedSelect.style.display="none",a.error({error:"Error",title:"Error",message:"❌ Oops! Something went wrong! Try reloading the page!"}),t.refreshButton.style.display="block"})}
//# sourceMappingURL=commonHelpers.js.map
